version: '3'

services:
  app:
    container_name: app
    build: ./src
    ports:
      - 8080:8080
    depends_on:
      - master_mysql
    restart: on-failure
  master_mysql:
    container_name: master_mysql
    image: mysql:5.6
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sample
      MYSQL_USER: sample_user
      MYSQL_PASSWORD: sample_password